language: node_js
node_js:
  - "6"
sudo: required
group: edge
services:
  - docker
install:
  - echo Hello docker!
script:
  - docker build . -t="macaca-sample/macaca-android-docker"
  - docker run -it "macaca-sample/macaca-android-docker" &
